### ISSUE TITLE
Unable to auto instrument go services due to the error trace ids must be 128 bit

### ISSUE THREAD

**Issue by dhanvsagar** [open-telemetry/opentelemetry-go-instrumentation#205]
### Describe the bug

Hi,
I am have a demo app (https://github.com/GoogleCloudPlatform/microservices-demo) deployed in a k8s cluster.
The services are in Java, NodeJS, .Net and Go.

I have the open telemetry operator installed in my cluster with featureGates: "operator.autoinstrumentation.go" to enable support for Go.

The app YAML files contains annotations as follows

```
 annotations:
        instrumentation.opentelemetry.io/inject-go: "true"
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/src/server"
```

My configured trace flow is as follows

``` [App + Auto Instrumentation] ---> OTel collector deployment --> Tempo --> Grafana ```

collector manifest as follows
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: demo
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s
    exporters:
      logging:
      otlp:
        endpoint: 'demo-tempo:4317'
        tls:
          insecure: true

    service:
      telemetry:
        logs:
          level: "debug"
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp]
```

Instrumentation.yaml

```
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: demo-instrumentation
spec:
  exporter:
    endpoint: http://demo-collector:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  python:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://demo-collector:4318
  dotnet:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://demo-collector:4318
```

### Environment

opentelemetry-operator-0.31.0                   
App Version 0.78.0

### To Reproduce

1. Create the OTel instrumentation and collector
2. Deploy the microservice
4. Check for errors

### Expected behavior

Traces must be flowing correctly to the collector and to tempo.

### Actual behavior

I can see the auto-instrumentation sidecar gets created and I don't see any errors in the log for the auto instrumentation.
```
{"level":"info","ts":1687267692.2892423,"caller":"opentelemetry/controller.go:74","msg":"got event","attrs":[{"Key":"http.method","Value":{"Type":"STRING","Value":"GET"}},{"Key":"http.target","Value":{"Type":"STRING","Value":"/_healthz"}}]}
{"level":"info","ts":1687267692.289315,"caller":"opentelemetry/controller.go:74","msg":"got event","attrs":[{"Key":"http.method","Value":{"Type":"STRING","Value":""}},{"Key":"http.target","Value":{"Type":"STRING","Value":""}}]}
{"level":"info","ts":1687267692.2893906,"caller":"opentelemetry/controller.go:74","msg":"got event","attrs":[{"Key":"http.method","Value":{"Type":"STRING","Value":""}},{"Key":"http.target","Value":{"Type":"STRING","Value":""}}]}
{"level":"info","ts":1687267702.289056,"caller":"opentelemetry/controller.go:74","msg":"got event","attrs":[{"Key":"http.method","Value":{"Type":"STRING","Value":"GET"}},{"Key":"http.target","Value":{"Type":"STRING","Value":"/_healthz"}}]}
{"level":"info","ts":1687267702.2891462,"caller":"opentelemetry/controller.go:74","msg":"got event","attrs":[{"Key":"http.method","Value":{"Type":"STRING","Value":"GET"}},{"Key":"http.target","Value":{"Type":"STRING","Value":"/_healthz"}}]}
{"level":"info","ts":1687267702.2891617,"caller":"opentelemetry/controller.go:74","msg":"got event","attrs":[{"Key":"http.method","Value":{"Type":"STRING","Value":"GET"}},{"Key":"http.target","Value":{"Type":"STRING","Value":"/_healthz"}}]}
{"level":"info","ts":1687267702.2891858,"caller":"opentelemetry/controller.go:74","msg":"got event","attrs":[{"Key":"http.method","Value":{"Type":"STRING","Value":""}},{"Key":"http.target","Value":{"Type":"STRING","Value":""}}]}
{"level":"info","ts":1687267702.2892082,"caller":"opentelemetry/controller.go:74","msg":"got event","attrs":[{"Key":"http.method","Value":{"Type":"STRING","Value":""}},{"Key":"http.target","Value":{"Type":"STRING","Value":""}}]}
{"level":"info","ts":1687267702.2892299,"caller":"opentelemetry/controller.go:74","msg":"got event","attrs":[{"Key":"http.method","Value":{"Type":"STRING","Value":"GET"}},{"Key":"http.target","Value":{"Type":"STRING","Value":"/_healthz"}}]}
{"level":"info","ts":1687267712.2893083,"caller":"opentelemetry/controller.go:74","msg":"got event","attrs":[{"Key":"http.method","Value":{"Type":"STRING","Value":"GET"}},{"Key":"http.target","Value":{"Type":"STRING","Value":"/_healthz"}}]}
{"level":"info","ts":1687267712.2893782,"caller":"opentelemetry/controller.go:74","msg":"got event","attrs":[{"Key":"http.method","Value":{"Type":"STRING","Value":"GET"}},{"Key":"http.target","Value":{"Type":"STRING","Value":"/_healthz"}}]}
{"level":"info","ts":1687267712.2894142,"caller":"opentelemetry/controller.go:74","msg":"got event","attrs":[{"Key":"http.method","Value":{"Type":"STRING","Value":""}},{"Key":"http.target","Value":{"Type":"STRING","Value":""}}]}
{"level":"info","ts":1687267712.2895224,"caller":"opentelemetry/controller.go:74","msg":"got event","attrs":[{"Key":"http.method","Value":{"Type":"STRING","Value":"GET"}},{"Key":"http.target","Value":{"Type":"STRING","Value":"/_healthz"}}]}
{"level":"info","ts":1687267712.2895997,"caller":"opentelemetry/controller.go:74","msg":"got event","attrs":[{"Key":"http.method","Value":{"Type":"STRING","Value":"GET"}},{"Key":"http.target","Value":{"Type":"STRING","Value":"/_healthz"}}]}
{"level":"info","ts":1687267712.2896292,"caller":"opentelemetry/controller.go:74","msg":"got event","attrs":[{"Key":"http.method","Value":{"Type":"STRING","Value":""}},{"Key":"http.target","Value":{"Type":"STRING","Value":""}}]}
```
But the OTel collector is unable to export the traces to tempo, and throws the error 
``` {"kind": "exporter", "data_type": "traces", "name": "otlp", "error": "Permanent error: rpc error: code = InvalidArgument desc = trace ids must be 128 bit", "dropped_items": 6}```

Error log from the Otel Collector
```
2023-06-20T13:30:25.751Z    error    exporterhelper/queued_retry.go:391    Exporting failed. The error is not retryable. Dropping data.    {"kind": "exporter", "data_type": "traces", "name": "otlp", "error": "Permanent error: rpc error: code = InvalidArgument desc = trace ids must be 128 bit", "dropped_items": 6}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
    go.opentelemetry.io/collector/exporter@v0.78.2/exporterhelper/queued_retry.go:391
go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesExporterWithObservability).send
    go.opentelemetry.io/collector/exporter@v0.78.2/exporterhelper/traces.go:126
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
    go.opentelemetry.io/collector/exporter@v0.78.2/exporterhelper/queued_retry.go:195
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1
    go.opentelemetry.io/collector/exporter@v0.78.2/exporterhelper/internal/bounded_memory_queue.go:47
2023-06-20T13:30:35.753Z    error    exporterhelper/queued_retry.go:391    Exporting failed. The error is not retryable. Dropping data.    {"kind": "exporter", "data_type": "traces", "name": "otlp", "error": "Permanent error: rpc error: code = InvalidArgument desc = trace ids must be 128 bit", "dropped_items": 6}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
    go.opentelemetry.io/collector/exporter@v0.78.2/exporterhelper/queued_retry.go:391
go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesExporterWithObservability).send
    go.opentelemetry.io/collector/exporter@v0.78.2/exporterhelper/traces.go:126
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
    go.opentelemetry.io/collector/exporter@v0.78.2/exporterhelper/queued_retry.go:195
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1
    go.opentelemetry.io/collector/exporter@v0.78.2/exporterhelper/internal/bounded_memory_queue.go:47
```

Error log from Tempo

```
level=error ts=2023-06-20T13:34:45.788034834Z caller=rate_limited_logger.go:27 msg="pusher failed to consume trace data" err="rpc error: code = InvalidArgument desc = trace ids must be 128 bit"
level=error ts=2023-06-20T13:34:55.789838072Z caller=rate_limited_logger.go:27 msg="pusher failed to consume trace data" err="rpc error: code = InvalidArgument desc = trace ids must be 128 bit"
level=error ts=2023-06-20T13:35:05.791289645Z caller=rate_limited_logger.go:27 msg="pusher failed to consume trace data" err="rpc error: code = InvalidArgument desc = trace ids must be 128 bit"
```

Please note that this error is only when I enable auto-instrumentation for the Go services and I don't see this error for NodeJS, Python and Java services.

Could you please help to resolve the issue.

(Please let me know if this should be an issue for the OTel Collector repos)
