### ISSUE TITLE
otel go instrumentation not working on bottlerocket

### ISSUE THREAD

**Issue by parthanand31-sudo** [open-telemetry/opentelemetry-go-instrumentation#2398]
### Describe the bug

When we are trying to run otel auto instrumentation as a sidecar container it is running fine in ubuntu nodes, but as soon as we run it in bottlerocket it throws an error
"level":"ERROR","source":{"function":"main.main","file":"/app/cli/main.go","line":125},"msg":"failed to load instrumentation","error":"program uprobe_writeSubset: load program: invalid argument: unknown func bpf_probe_write_user#36 (895 line(s) omitted)"}

Even after adding multiple security capabilities it is still the same and not able to work. Bottlerocket states it allows SELinux  

### Environment

 - OS: Bottlerocket amazon/bottlerocket-aws-k8s-1.29-x86_64-v1
 - Go Version: go1.24.0

### To Reproduce

**Add the nodeselector as bottlerocket ASG, it gives this error**
`{"function":"main.main","file":"/app/cli/main.go","line":125},"msg":"failed to load instrumentation","error":"program uprobe_writeSubset: load program: invalid argument: unknown **func bpf_probe_write_user**#36 (895 line(s) omitted)"}`

And when you try to add security extra **security capabilit**y sharing below, it gives error as  where **exe_path is correct and same path works in ubuntu nodes.**
`**`{"time":"2025-05-28T18:18:46.565749439Z","level":"DEBUG","source":{"function":"go.opentelemetry.io/auto/internal/pkg/process.(*Analyzer).DiscoverProcessID","file":"/app/internal/pkg/process/discover.go","line":68},"**msg":"process not found yet, trying again soon","exe_path":"/app/vault"**}`**:`
        

```
securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            - SYS_PTRACE
            - SYS_ADMIN
          seccompProfile:
            type: Unconfined
          runAsUser: 0
          privileged: true
```

We are trying this with a version of v0.21.0, **with v0.22.0, it gives error as**:
msg":"failed to create instrumentation","error":"invalid dependency version github.com/razorpay/payment-card ((devel)): **Invalid Semantic Version**"}

### Expected behavior

As per bottle rocket FAQ's it supports ebpf based, but why otel is not able to read is what we need to find out and need help with.
Couple of other applications which also used ebpf based tech, by enabling security context capabilites, it used to work, but for otel auto instrumentation use case it did not worked.
