### ISSUE TITLE
when trying go auto instrumentation I got process not found yet

### ISSUE THREAD

**Issue by msherif1234** [open-telemetry/opentelemetry-go-instrumentation#520]
### Describe the bug

Not sure how to make my go app visible to instrumentation pod
### Environment

running on OCP cluster 

### To Reproduce

1. install cert-manager 
`kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.2/cert-manager.yaml `
2. deploy optel operator
`kubectl apply -f https://github.com/open-telemetry/opentelemetry-operator/releases/latest/download/opentelemetry-operator.yaml`
3. create optel collector object
```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: demo
  namespace: default
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      # NOTE: Prior to v0.86.0 use  instead of .
      debug:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
  mode: daemonset
```
4. create instrumentation object
```yaml
kubectl apply -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: demo-instrumentation
spec:
  exporter:
    endpoint: http://demo-collector:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
EOF
```
5. using https://github.com/netobserv/network-observability-operator/pull/500 PR to hack the netobserv operator and enable auto instrumentation for now we need to set `OTEL_EXPORTER_OTLP_ENDPOINT` manually to match optel svcIP then compile 
`make image-build` then `make image-push`
then deploy operator
`USER=username VERSION="main-amd64" make deploy`

6. create netobserv flow collector
`oc create -f config/samples/flows_v1beta2_flowcollector.yaml`
7. we should see netobserv agent pods now running with two containers with new one as sidecar for instrumentation
```shell
oc get pods -n netobserv-privileged
NAME                         READY   STATUS    RESTARTS   AGE
netobserv-ebpf-agent-2msml   2/2     Running   0          24m
netobserv-ebpf-agent-7grl5   2/2     Running   0          24m
netobserv-ebpf-agent-8pgwj   2/2     Running   0          24m
netobserv-ebpf-agent-n9s6q   2/2     Running   0          24m
netobserv-ebpf-agent-trq4b   2/2     Running   0          24m
netobserv-ebpf-agent-whqxs   2/2     Running   0          24m
```
### Expected behavior

I was expected to instrumentation container to find the app binary and start emitting some form of metrics  but I am getting 
```shell
{"level":"info","ts":1700489757.6685278,"logger":"Instrumentation.Analyzer","caller":"process/discover.go:73","msg":"process not found yet, trying again soon","exe_path":"/netobserv-ebpf-agent"}
```
### Additional context

Used instructions doc here https://opentelemetry.io/docs/kubernetes/operator/automatic/
