### ISSUE TITLE
auto instrument failed: offset not found: net/http.response:status

### ISSUE THREAD

**Issue by droger88** [open-telemetry/opentelemetry-go-instrumentation#732]
### Describe the bug

We are using go auto instrumentation with opentelemetry operator, the sidecar container is not able to start due to the following error
```
{"level":"error","ts":1711045263.4401302,"logger":"Instrumentation.Manager","caller":"instrumentation/manager.go:175","msg":"error while loading probes, cleaning up","name":"net/http/server","error":"offset not found: net/http.response:status (1.21.8)","stacktrace":"go.opentelemetry.io/auto/internal/pkg/instrumentation.(*Manager).load\n\t/app/internal/pkg/instrumentation/manager.go:175\ngo.opentelemetry.io/auto/internal/pkg/instrumentation.(*Manager).Run\n\t/app/internal/pkg/instrumentation/manager.go:125\ngo.opentelemetry.io/auto.(*Instrumentation).Run\n\t/app/instrumentation.go:152\nmain.main\n\t/app/cli/main.go:108\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267"}
{"level":"info","ts":1711045263.4401646,"logger":"Instrumentation.Manager.net/http/server","caller":"probe/probe.go:213","msg":"Closed","Probe":"net/http/server"}
{"level":"info","ts":1711045263.4401739,"logger":"Instrumentation.Manager","caller":"instrumentation/manager.go:200","msg":"Cleaning bpffs"}
{"level":"error","ts":1711045263.4401944,"logger":"go.opentelemetry.io/auto","caller":"cli/main.go:109","msg":"instrumentation crashed","error":"offset not found: net/http.response:status (1.21.8)","stacktrace":"main.main\n\t/app/cli/main.go:109\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267"}
```

### Environment

 - Go Version:  go1.19.3 darwin/arm64
 - Instrument version: otel/autoinstrumentation-go:v0.10.1-alpha
 
### To Reproduce

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-go: "monitoring/instrumentation"
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: '/app/server'
    spec:
      containers:
        - name: app
          image: app-image
          env:
          - name: OTEL_SERVICE_NAME
            value: my-api-dev
```
### Expected behavior

sidecar instrument successfully starts

### Additional context
we used to use `otel/autoinstrumentation-go:v0.7.0-alpha`, and it works.
