### ISSUE TITLE
Can't get container.id from auto instrumentation

### ISSUE THREAD

**Issue by ivalba** [open-telemetry/opentelemetry-go-instrumentation#797]
### Describe the bug

I'm using auto instrumentation in an minikube cluster running 1 pod (3 replicas), each pod has 2 containers:
1) simple go http server
2) auto instrumentation container

Traces are working fine except for container.id (I need it for infra correlation in the platform that I'm using (Cisco Cloud Observability))

I'm trying to use OTEL_RESOURCE_ATTRIBUTES to get the container.id through a script recalling /proc/self/mountinfo but I can't get the id. Running the command inside the container shell works fine.

this is my deployment YAML:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: ivango
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      shareProcessNamespace: true
      containers:
      - name: myapp
        image: myapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      - name: autoinstrumentation-go
        image: otel/autoinstrumentation-go
        imagePullPolicy: IfNotPresent
        env:
          - name: OTEL_GO_AUTO_TARGET_EXE
            value: /app/myapp
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://10.108.129.85:4318"
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: service.name=GO-Service-Ivan,service.namespace=ivango,k8s.namespace.name=ivango,container.id=$(cat /proc/self/mountinfo | grep -m1 -oE 'docker/containers/([a-f0-9]+)/' | xargs basename)
        securityContext:
          runAsUser: 0
          privileged: true
```

The result is that I can see correctly all the traces, but instead of the container.id I get the script code itself:

<img width="247" alt="image" src="https://github.com/open-telemetry/opentelemetry-go-instrumentation/assets/137791787/30feade8-afbc-4c02-ac25-6651404aa643">

This is my DockerFile:

```dockerfile
FROM golang:1.16 as builder

WORKDIR /app
COPY . .

RUN go mod init example.com/myapp
RUN CGO_ENABLED=0 GOOS=linux go build -o myapp

FROM alpine:3.14

WORKDIR /app
COPY --from=builder /app/myapp /app/

EXPOSE 8080
CMD ["/app/myapp"]
```
And this is my main.go

```go
package main

import (
	"fmt"
	"net/http"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, "Hello, Kubernetes!")
	})

	http.ListenAndServe(":8080", nil)
}
```
### Environment

 - OS: Amazon Linux
 - Go Version: 1.16
 - Version:  v0.12.0-alpha

### To Reproduce

1. Build a docker image of main.go
2. Create a minikube cluster
3. Apply the deployment.yaml
4. See on the otel platform the script instead of the container.id

### Expected behavior

Seeing the container.id coming from the auto instrumented golang application container
