### ISSUE TITLE
Why do we use - /proc:/host/proc instead of - /proc:/proc ?

### ISSUE THREAD

**Issue by s4s7** [open-telemetry/opentelemetry-go-instrumentation#841]
I was going through the source code and the documentation, specifically in the docker compose volume mapping.

> 2. Edit the docker-compose file to add a new service for the instrumentation:

  ```yaml
    go-auto:
      image: otel/autoinstrumentation-go
      privileged: true
      pid: "host"
      environment:
        - OTEL_EXPORTER_OTLP_ENDPOINT=http://<address_in_docker_network>:4318
        - OTEL_GO_AUTO_TARGET_EXE=<location_of_target_application_binary>
        - OTEL_SERVICE_NAME=<name_of_your_application>
        - OTEL_PROPAGATORS=tracecontext,baggage
      volumes:
        - <shared_volume_of_application>
        - /proc:/host/proc
  ```
  
Could anyone explain why we are using /host/proc instead of /proc? 
In the source code I don't see any /host/proc references. I only see /proc.
